services:
  web:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: dark-web
    restart: always
    expose:
      - "80"
    networks:
      - deploy_net 
    volumes:
      - deploy_sqlite_dir:/data

networks:
  deploy_net:
    external: true

volumes:
  deploy_sqlite_dir: 
    external: true
